name: Main

# Schedule to run every day at midnight UTC
on:
  schedule:
  - cron: "0 0 * * *"

  # Allow workflow to be run manually
  workflow_dispatch:

# Jobs to complete
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Get the latest BD release from main repo
      - name: Fetch Github Release Assets
        uses: Itsblue/download-release-assets-action@v4
        with:
          # Download latest release BD CSS file
          repo: 'TakosThings/Metro-for-Discord'
          version: 'latest'
          file: 'Metro_for_Discord.theme.css'
          # Output path for the downloaded files
          path: 'dist'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Add BD CSS & Commit
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
          add: 'dist/Metro_for_Discord.theme.css'
          branch: master
          # How the action should fill missing author name or email.
          default_author: github_actor
          # Commit message
          message: 'Commit from GitHub Actions - Main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
